/**
 * Regenerate `src/lib/symbol-table.ts` from Trading 212's instrument catalogue.
 *
 * Trading 212 states the real market symbol in `TradableInstrument.shortName`:
 * `ABML_US_EQ` is `ABAT`, `TNP_US_EQ` is `TEN`. The addon cannot read that
 * field, because the catalogue is a single 4.2 MB response — the endpoint
 * ignores `search`, `ticker` and `limit` alike, so there is no smaller form to
 * ask for — and Wealthfolio's network broker refuses a response that large.
 *
 * So the catalogue is read here, under Node where no such limit applies, and
 * reduced to the cases the ticker rule gets wrong: about 2,100 of 17,400, some
 * 40 KB. Bundling those turns a 87.8% guess into an exact lookup.
 *
 * Re-run it when Trading 212 lists something new or a company renames:
 *
 *   pnpm symbols:generate
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { T212 } from 't212-sdk';
import { EXCHANGE_MIC, T212_ENVIRONMENT } from '../src/config';
import { requireCredentials } from '../../../tools/credentials';

const { apiKey, apiSecret } = requireCredentials();

console.log('Fetching the Trading 212 instrument catalogue…');
const client = new T212({ apiKey, apiSecret, environment: T212_ENVIRONMENT });
const instruments = await client.instruments.list();
console.log(`  ${instruments.length} instruments.`);

console.log('Fetching exchanges…');
const exchanges = await client.instruments.exchanges();
// `workingScheduleId` is the only link Trading 212 gives from an instrument to
// its venue, and it is stated, not inferred.
const venueBySchedule = new Map<number, string>();
for (const exchange of exchanges) {
  for (const schedule of exchange.workingSchedules ?? []) {
    venueBySchedule.set(schedule.id, exchange.name);
  }
}

const table: Record<string, string> = {};
let missingVenue = 0;
for (const instrument of instruments) {
  const shortName = instrument.shortName?.trim();
  if (!shortName) continue;
  const venue = venueBySchedule.get(instrument.workingScheduleId);
  const mic = venue ? (EXCHANGE_MIC[venue] ?? '') : '';
  if (venue && EXCHANGE_MIC[venue] === undefined) missingVenue += 1;
  // "SYMBOL|MIC|CURRENCY". The MIC is empty when Trading 212 names a venue with
  // no market identifier code, such as OTC Markets.
  //
  // The currency is `currencyCode` verbatim, pence and all. It is what the
  // instrument's *quotes* are denominated in, which is not always what its
  // trades are: this addon converts a pence fill to pounds when it writes the
  // activity, so the activity says GBP while the price feed still says GBX.
  // Reading the currency back off an activity therefore says nothing about the
  // quote, and doing so once turned every London pence holding into a figure a
  // hundred times too large.
  const currency = instrument.currencyCode?.trim() ?? '';
  table[instrument.ticker] = `${shortName}|${mic}|${currency}`;
}
if (missingVenue > 0) {
  console.warn(`  ${missingVenue} instruments sit on a venue with no EXCHANGE_MIC entry — add it in config.ts.`);
}

const entries = Object.entries(table).sort(([a], [b]) => a.localeCompare(b));
const body = entries.map(([ticker, value]) => `  ${JSON.stringify(ticker)}: ${JSON.stringify(value)},`).join('\n');

const file = `/**
 * What Trading 212 says each of its tickers is, as \`"SYMBOL|MIC|CURRENCY"\`.
 *
 * GENERATED by \`pnpm symbols:generate\` — do not edit by hand.
 *
 * Every value here is a field Trading 212 states outright: \`shortName\` for the
 * symbol, the venue reached through \`workingScheduleId\`, and \`currencyCode\`
 * for what its quotes are priced in. Nothing is parsed
 * out of the ticker. That matters because the ticker looks like it encodes the
 * answer and does not — \`ABML_US_EQ\` is ABAT, not ABML, because the company
 * renamed and Trading 212 kept the original code.
 *
 * The table is bundled rather than fetched because the catalogue is a single
 * 4.2 MB response, which exceeds Wealthfolio's addon network broker limit, and
 * the endpoint ignores \`search\`, \`ticker\` and \`limit\` alike — there is no
 * smaller form to ask for.
 *
 * A ticker absent from this table is *unknown*, not guessable. Regenerate when
 * Trading 212 lists something new or a holding renames.
 */
export const SYMBOL_TABLE: Record<string, string> = {
${body}
};
`;

const target = resolve(import.meta.dirname, '../src/lib/symbol-table.ts');
writeFileSync(target, file);
console.log(`Wrote ${entries.length} instruments (${(file.length / 1024).toFixed(0)} KB) to src/lib/symbol-table.ts`);
